In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.3


In [4]:
# array creation
list=[10, 20, 30, 40, 50]
arr = np.array(list)
print(arr)
print('Type:', type(arr))
print('Shape:', arr.shape)

[10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Shape: (5,)


In [15]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print("------------------------------")
print('Shape:', arr2.shape)
print("------------------------------")
print('Shape:', arr2.size)
print("------------------------------")
print(arr2[0])
print("------------------------------")
print(arr2[0][2]) #print first row second column

[[1 2 3]
 [4 5 6]]
------------------------------
Shape: (2, 3)
------------------------------
Shape: 6
------------------------------
[1 2 3]
------------------------------
3


In [19]:
#generate arrays

print(np.zeros((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
arr2 = np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
arr3 = np.arange(1,10,3)
print(arr3)

[1 4 7]


In [26]:
sample = np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [30]:
a = np.arange(1,10,3)
b = np.arange(2,10,3)

print(a+b)
print("-------------------------------")
print(a*b)
print("-------------------------------")
print(a**2)


[ 3  9 15]
-------------------------------
[ 2 20 56]
-------------------------------
[ 1 16 49]


In [34]:
purchases = np.array([
    [200,150,100],
    [300,250,400],
    [100,200,150],
    [500,600,550],
    [50,80,100],
])
#axis = 1 is horizontal calculation and axis = 0 means vertical calculation
total_spend = purchases.sum(axis=1)

average_spend = purchases.mean(axis=1)

print("Total Spend: ",total_spend)
print("-------------------------------")
print("Average Spend: ",average_spend)
print("-------------------------------")
print(max(average_spend))

Total Spend:  [ 450  950  450 1650  230]
-------------------------------
Average Spend:  [150.         316.66666667 150.         550.          76.66666667]
-------------------------------
550.0


In [36]:
# 2x+3y = 8
#4x+y=10

#coefficients of variables

A = np.array([[2,3],[4,1]])

#constants on the right hand side

B = np.array([8,10])

solution = np.linalg.solve(A,B)

print("Solution (x,y):", solution)

Solution (x,y): [2.2 1.2]


#activity

In [53]:
sales = np.array([1000, 1200, 1300, 1400, 1500, 8890, 4122, 4358, 9075, 2356])
print("Total sales: ",sales.sum())
print("Average sales: ",np.average(sales))
print("Maximum sales: ",sales.max())
print("Minimum sales: ",sales.min())

Total sales:  35201
Average sales:  3520.1
Maximum sales:  9075
Minimum sales:  1000


In [47]:
arr = sales*1.10
print(arr)

[1100.  1320.  1430.  1540.  1650.  9779.  4534.2 4793.8 9982.5 2591.6]


In [49]:
print(np.sort(sales))

[1000 1200 1300 1400 1500 2356 4122 4358 8890 9075]


In [52]:
print("Sales higher than average: ", sales[sales>np.average(sales)])


Sales higher than average:  [4122 4358 8890 9075]


In [54]:
import pandas as pd

In [55]:
df = pd.read_csv('new.csv')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Order_ID      10 non-null     int64  
 1   Product       10 non-null     object 
 2   Category      10 non-null     object 
 3   Quantity      10 non-null     int64  
 4   Price         10 non-null     int64  
 5   Total_Amount  0 non-null      float64
 6   Date          10 non-null     object 
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes


In [57]:
df.isna() #to check null values

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [63]:
df = df.fillna(0) #handling missing values.here we are filling the null values with 0

In [64]:
df.duplicated()


0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [65]:
print(df)

   Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10  


In [66]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [67]:
pd.to_datetime(df['Date'],)


0   2024-02-01
1   2024-02-02
2   2024-02-03
3   2024-02-04
4   2024-02-05
5   2024-02-06
6   2024-02-07
7   2024-02-08
8   2024-02-09
9   2024-02-10
Name: Date, dtype: datetime64[ns]

In [68]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [71]:
df['Product'] = df['Product'].astype(str)
df['Category'] = df['Category'].astype(str)
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [72]:
df['Quantity'] = df['Quantity'].astype(int)

In [73]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

#outlier

In [78]:
data = np.array([10, 12, 34, 56, 78, 90, 100])

q1 = np.percentile(data,25)
q3 = np.percentile(data,75)

IQR = q3-q1

lower_bound = q1-1.5*IQR
upper_bound = q3+1.5*IQR

outliers = data[(data<lower_bound)|(data>upper_bound)]

print("Outliers: ", outliers)

Outliers:  []
